# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Dependencies
markdown:       kramdown
highlighter:    rouge

# Setup
title:          Jinwuk Seok's Mathematical Pages
email:          sderoen@gmail.com
description:    Jinwuk Seok's Blog about the mathematical issues with respect to stochastic calculus, differential geometry, control, and video processing.

url:            https://Jinwuk.github.io 
                  # the base hostname & protocol for your site, e.g. http://example.com
 

baseurl:        "" 
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

twitter_username: sderoen
github_username:  Jinwuk

author:
  name:           'Jinwuk Seok'
  url:            https://twitter.com/sderoen

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# -----------------------------------------------------------------------------
#  Collections
# -----------------------------------------------------------------------------
collections:
  projects:
    permalink:       /projects/:path/
    output:          true

# Custom vars
version:            0.0.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

# Fallback image and color
#image:               /assets/img/space.png

github:
  repo:             https://github.com/Jinwuk/Jinwuk.github.io

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true
#  footnote_backlink: '&#x21a9;&#xfe0e;'

  
# Comment
disqus:
  shortname: jinwuk

  
# Set your Google Analytics id and Google Adsense id to receive `pageview` events.
# To remove Google Anaylics or Google Adsense from your page, remove the line below.
google_analytics: UA-122676285-1
google_ad_client: ca-pub-2352406350095521

